name: Backend CI

on:
  workflow_dispatch:   # manual trigger
  push:
    branches:
      - production
      - staging
      - development
    paths:
      - "my-backend-app/**"  # trigger only if backend files change
  pull_request:
    branches:
      - production
      - staging
      - development
    paths:
      - "my-backend-app/**"  # trigger only if backend files change

jobs:
  backend-ci:
    name: Backend CI
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: my-backend-app  # CI runs only in backend folder

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm test
